# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from qa_split_grpc_client.api.system_v1 import system_v1_pb2 as qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2


class SystemV1Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFeatureFlagList = channel.unary_unary(
                '/wms.go.service.batching.split.system.v1.SystemV1/GetFeatureFlagList',
                request_serializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.GetFeatureFlagListRequest.SerializeToString,
                response_deserializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.GetFeatureFlagListResponse.FromString,
                )
        self.LinkFeatureFlag = channel.unary_unary(
                '/wms.go.service.batching.split.system.v1.SystemV1/LinkFeatureFlag',
                request_serializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.LinkFeatureFlagRequest.SerializeToString,
                response_deserializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.LinkFeatureFlagResponse.FromString,
                )
        self.UnlinkFeatureFlag = channel.unary_unary(
                '/wms.go.service.batching.split.system.v1.SystemV1/UnlinkFeatureFlag',
                request_serializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.UnlinkFeatureFlagRequest.SerializeToString,
                response_deserializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.UnlinkFeatureFlagResponse.FromString,
                )
        self.V1GetSplitRestrictions = channel.unary_unary(
                '/wms.go.service.batching.split.system.v1.SystemV1/V1GetSplitRestrictions',
                request_serializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1GetSplitRestrictionsRequest.SerializeToString,
                response_deserializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1GetSplitRestrictionsResponse.FromString,
                )
        self.V1CreateSplitRestrictions = channel.unary_unary(
                '/wms.go.service.batching.split.system.v1.SystemV1/V1CreateSplitRestrictions',
                request_serializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1CreateSplitRestrictionsRequest.SerializeToString,
                response_deserializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1CreateSplitRestrictionsResponse.FromString,
                )
        self.V1UpdateSplitRestrictions = channel.unary_unary(
                '/wms.go.service.batching.split.system.v1.SystemV1/V1UpdateSplitRestrictions',
                request_serializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1UpdateSplitRestrictionsRequest.SerializeToString,
                response_deserializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1UpdateSplitRestrictionsResponse.FromString,
                )


class SystemV1Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFeatureFlagList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkFeatureFlag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlinkFeatureFlag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def V1GetSplitRestrictions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def V1CreateSplitRestrictions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def V1UpdateSplitRestrictions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemV1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFeatureFlagList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatureFlagList,
                    request_deserializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.GetFeatureFlagListRequest.FromString,
                    response_serializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.GetFeatureFlagListResponse.SerializeToString,
            ),
            'LinkFeatureFlag': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkFeatureFlag,
                    request_deserializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.LinkFeatureFlagRequest.FromString,
                    response_serializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.LinkFeatureFlagResponse.SerializeToString,
            ),
            'UnlinkFeatureFlag': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlinkFeatureFlag,
                    request_deserializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.UnlinkFeatureFlagRequest.FromString,
                    response_serializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.UnlinkFeatureFlagResponse.SerializeToString,
            ),
            'V1GetSplitRestrictions': grpc.unary_unary_rpc_method_handler(
                    servicer.V1GetSplitRestrictions,
                    request_deserializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1GetSplitRestrictionsRequest.FromString,
                    response_serializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1GetSplitRestrictionsResponse.SerializeToString,
            ),
            'V1CreateSplitRestrictions': grpc.unary_unary_rpc_method_handler(
                    servicer.V1CreateSplitRestrictions,
                    request_deserializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1CreateSplitRestrictionsRequest.FromString,
                    response_serializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1CreateSplitRestrictionsResponse.SerializeToString,
            ),
            'V1UpdateSplitRestrictions': grpc.unary_unary_rpc_method_handler(
                    servicer.V1UpdateSplitRestrictions,
                    request_deserializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1UpdateSplitRestrictionsRequest.FromString,
                    response_serializer=qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1UpdateSplitRestrictionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wms.go.service.batching.split.system.v1.SystemV1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SystemV1(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFeatureFlagList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wms.go.service.batching.split.system.v1.SystemV1/GetFeatureFlagList',
            qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.GetFeatureFlagListRequest.SerializeToString,
            qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.GetFeatureFlagListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LinkFeatureFlag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wms.go.service.batching.split.system.v1.SystemV1/LinkFeatureFlag',
            qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.LinkFeatureFlagRequest.SerializeToString,
            qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.LinkFeatureFlagResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnlinkFeatureFlag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wms.go.service.batching.split.system.v1.SystemV1/UnlinkFeatureFlag',
            qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.UnlinkFeatureFlagRequest.SerializeToString,
            qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.UnlinkFeatureFlagResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def V1GetSplitRestrictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wms.go.service.batching.split.system.v1.SystemV1/V1GetSplitRestrictions',
            qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1GetSplitRestrictionsRequest.SerializeToString,
            qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1GetSplitRestrictionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def V1CreateSplitRestrictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wms.go.service.batching.split.system.v1.SystemV1/V1CreateSplitRestrictions',
            qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1CreateSplitRestrictionsRequest.SerializeToString,
            qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1CreateSplitRestrictionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def V1UpdateSplitRestrictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wms.go.service.batching.split.system.v1.SystemV1/V1UpdateSplitRestrictions',
            qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1UpdateSplitRestrictionsRequest.SerializeToString,
            qa__split__grpc__client_dot_api_dot_system__v1_dot_system__v1__pb2.V1UpdateSplitRestrictionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
