# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from qa_split_grpc_client.api.v2 import split_pb2 as qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2


class SplitStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SplitPosting = channel.unary_unary(
                '/ozon.wms.go.service.batching.split.api.v2.Split/SplitPosting',
                request_serializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingRequest.SerializeToString,
                response_deserializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingResponse.FromString,
                )
        self.SplitPostingWhComm = channel.unary_unary(
                '/ozon.wms.go.service.batching.split.api.v2.Split/SplitPostingWhComm',
                request_serializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingWhCommRequest.SerializeToString,
                response_deserializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingWhCommResponse.FromString,
                )
        self.AddPostingsSplitReasons = channel.unary_unary(
                '/ozon.wms.go.service.batching.split.api.v2.Split/AddPostingsSplitReasons',
                request_serializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.PostingsSplitReasonsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SplitPostingByTags = channel.unary_unary(
                '/ozon.wms.go.service.batching.split.api.v2.Split/SplitPostingByTags',
                request_serializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingRequest.SerializeToString,
                response_deserializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingResponse.FromString,
                )


class SplitServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SplitPosting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SplitPostingWhComm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPostingsSplitReasons(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SplitPostingByTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SplitServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SplitPosting': grpc.unary_unary_rpc_method_handler(
                    servicer.SplitPosting,
                    request_deserializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingRequest.FromString,
                    response_serializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingResponse.SerializeToString,
            ),
            'SplitPostingWhComm': grpc.unary_unary_rpc_method_handler(
                    servicer.SplitPostingWhComm,
                    request_deserializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingWhCommRequest.FromString,
                    response_serializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingWhCommResponse.SerializeToString,
            ),
            'AddPostingsSplitReasons': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPostingsSplitReasons,
                    request_deserializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.PostingsSplitReasonsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SplitPostingByTags': grpc.unary_unary_rpc_method_handler(
                    servicer.SplitPostingByTags,
                    request_deserializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingRequest.FromString,
                    response_serializer=qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ozon.wms.go.service.batching.split.api.v2.Split', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Split(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SplitPosting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ozon.wms.go.service.batching.split.api.v2.Split/SplitPosting',
            qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingRequest.SerializeToString,
            qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SplitPostingWhComm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ozon.wms.go.service.batching.split.api.v2.Split/SplitPostingWhComm',
            qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingWhCommRequest.SerializeToString,
            qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingWhCommResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddPostingsSplitReasons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ozon.wms.go.service.batching.split.api.v2.Split/AddPostingsSplitReasons',
            qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.PostingsSplitReasonsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SplitPostingByTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ozon.wms.go.service.batching.split.api.v2.Split/SplitPostingByTags',
            qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingRequest.SerializeToString,
            qa__split__grpc__client_dot_api_dot_v2_dot_split__pb2.SplitPostingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
