# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from qa_split_grpc_client.api.qa import qa_pb2 as qa__split__grpc__client_dot_api_dot_qa_dot_qa__pb2


class QaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RemoveOldest = channel.unary_unary(
                '/ozon.wms.go.service.batching.split.api.qa.Qa/RemoveOldest',
                request_serializer=qa__split__grpc__client_dot_api_dot_qa_dot_qa__pb2.RemoveOldestRequest.SerializeToString,
                response_deserializer=qa__split__grpc__client_dot_api_dot_qa_dot_qa__pb2.RemoveOldestResponse.FromString,
                )


class QaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RemoveOldest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RemoveOldest': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveOldest,
                    request_deserializer=qa__split__grpc__client_dot_api_dot_qa_dot_qa__pb2.RemoveOldestRequest.FromString,
                    response_serializer=qa__split__grpc__client_dot_api_dot_qa_dot_qa__pb2.RemoveOldestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ozon.wms.go.service.batching.split.api.qa.Qa', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Qa(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RemoveOldest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ozon.wms.go.service.batching.split.api.qa.Qa/RemoveOldest',
            qa__split__grpc__client_dot_api_dot_qa_dot_qa__pb2.RemoveOldestRequest.SerializeToString,
            qa__split__grpc__client_dot_api_dot_qa_dot_qa__pb2.RemoveOldestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
