# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qa_split_grpc_client/api/qa/qa.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qa_split_grpc_client/api/qa/qa.proto',
  package='ozon.wms.go.service.batching.split.api.qa',
  syntax='proto3',
  serialized_options=b'Z3gitlab.ozon.ru/wms/go/service/batching/split/pkg/qa\252\002%Ozon.Wms.Go.Service.Batching.Split.QA',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$qa_split_grpc_client/api/qa/qa.proto\x12)ozon.wms.go.service.batching.split.api.qa\"\x15\n\x13RemoveOldestRequest\"\x16\n\x14RemoveOldestResponse2\x96\x01\n\x02Qa\x12\x8f\x01\n\x0cRemoveOldest\x12>.ozon.wms.go.service.batching.split.api.qa.RemoveOldestRequest\x1a?.ozon.wms.go.service.batching.split.api.qa.RemoveOldestResponseB]Z3gitlab.ozon.ru/wms/go/service/batching/split/pkg/qa\xaa\x02%Ozon.Wms.Go.Service.Batching.Split.QAb\x06proto3'
)




_REMOVEOLDESTREQUEST = _descriptor.Descriptor(
  name='RemoveOldestRequest',
  full_name='ozon.wms.go.service.batching.split.api.qa.RemoveOldestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=104,
)


_REMOVEOLDESTRESPONSE = _descriptor.Descriptor(
  name='RemoveOldestResponse',
  full_name='ozon.wms.go.service.batching.split.api.qa.RemoveOldestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['RemoveOldestRequest'] = _REMOVEOLDESTREQUEST
DESCRIPTOR.message_types_by_name['RemoveOldestResponse'] = _REMOVEOLDESTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RemoveOldestRequest = _reflection.GeneratedProtocolMessageType('RemoveOldestRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEOLDESTREQUEST,
  '__module__' : 'qa_split_grpc_client.api.qa.qa_pb2'
  # @@protoc_insertion_point(class_scope:ozon.wms.go.service.batching.split.api.qa.RemoveOldestRequest)
  })
_sym_db.RegisterMessage(RemoveOldestRequest)

RemoveOldestResponse = _reflection.GeneratedProtocolMessageType('RemoveOldestResponse', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEOLDESTRESPONSE,
  '__module__' : 'qa_split_grpc_client.api.qa.qa_pb2'
  # @@protoc_insertion_point(class_scope:ozon.wms.go.service.batching.split.api.qa.RemoveOldestResponse)
  })
_sym_db.RegisterMessage(RemoveOldestResponse)


DESCRIPTOR._options = None

_QA = _descriptor.ServiceDescriptor(
  name='Qa',
  full_name='ozon.wms.go.service.batching.split.api.qa.Qa',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=131,
  serialized_end=281,
  methods=[
  _descriptor.MethodDescriptor(
    name='RemoveOldest',
    full_name='ozon.wms.go.service.batching.split.api.qa.Qa.RemoveOldest',
    index=0,
    containing_service=None,
    input_type=_REMOVEOLDESTREQUEST,
    output_type=_REMOVEOLDESTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_QA)

DESCRIPTOR.services_by_name['Qa'] = _QA

# @@protoc_insertion_point(module_scope)
